"""Domain constants and configuration values."""

# VSA Engine Constants
VOLUME_SPIKE_THRESHOLD = 2.0
PRICE_CHANGE_THRESHOLD = 0.015
LOOKBACK_PERIOD = 20
VOLATILITY_WINDOW = 14

# Risk Management Constants
DEFAULT_RISK_PER_TRADE = 0.02
MAX_POSITION_SIZE = 0.25
STOP_LOSS_PERCENT = 0.05
TAKE_PROFIT_PERCENT = 0.10

# Trading Constants
MIN_BAR_PRICE = 0.01
MAX_BAR_PRICE = 1000000.0
DEFAULT_COMMISSION = 0.0005
DEFAULT_SLIPPAGE = 0.001

# AI/ML Constants
DEFAULT_SEQUENCE_LENGTH = 60
DEFAULT_HIDDEN_SIZE = 64
DEFAULT_NUM_LAYERS = 2
DEFAULT_DROPOUT = 0.2
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_BATCH_SIZE = 32
DEFAULT_EPOCHS = 50
EARLY_STOPPING_PATIENCE = 10

# Scanner Constants
SCAN_INTERVAL_MINUTES = 5
MIN_LIQUIDITY_RUB = 1000000
MAX_POSITIONS = 10

# Market Constants
MARKET_OPEN_HOUR = 10
MARKET_CLOSE_HOUR = 19
TIMEZONE = "Europe/Moscow"
